-- phpMyAdmin SQL Dump
-- version 4.9.4
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Generation Time: Apr 09, 2020 at 10:10 AM
-- Server version: 10.3.22-MariaDB
-- PHP Version: 7.3.6

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `androlov_islamic`
--

-- --------------------------------------------------------

--
-- Table structure for table `books`
--

CREATE TABLE `books` (
  `id` int(11) NOT NULL,
  `image_url` varchar(1000) NOT NULL,
  `book_url` varchar(1000) NOT NULL,
  `book_name` varchar(1000) NOT NULL,
  `title` varchar(1000) NOT NULL,
  `size` varchar(1000) NOT NULL,
  `des` varchar(1000) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Dumping data for table `books`
--

INSERT INTO `books` (`id`, `image_url`, `book_url`, `book_name`, `title`, `size`, `des`) VALUES
(1, 'https://androlover.com/islamic/images/1img1.jpg', 'https://androlover.com/islamic/books/1B1.pdf', 'IB1.pdf', '4pyUICDhgKHhgIXhgaXhgJzhgKzhgJnhgLnhgLfhgJvhgojhgLHhgJHhgKzhgIThgLnhgLcg4YCC4YC64YCE4YC54YCU4YC54YCb4YKI4YCt4YCA4YC54YCe4YC84YCs4YCU4YC54YCx4YCc4YCs4YCA', '4pyUICBGaWxlIFNpemU6IDEzLjUgTUI=', '4pyUICDhgLvhgJXhgLPhgIXhgK/hgLHhgJvhgLjhgJ7hgKzhgLjhgJ7hgLA6IOGAoeGAnOGAueGAn+GAguGAuuGAuSDhgLHhgJnhgKzhgLnhgJzhgKzhgJThgKzhgJnhgK/hgJbhgLnhgJ7hgK7hgIDhgKzhgJvhgK4g4YCZ4YCv4YCf4YCZ4YG84YCS4YC54YCa4YCw4YCF4YC84YCW4YC5'),
(2, 'https://androlover.com/islamic/images/img2.jpg', 'https://androlover.com/islamic/books/B2.pdf', 'IB2.pdf', '4pyUIOGAoeGAgeGAuuGAreGAs+GClOGAmeGAvOGAkOGAueGAheGAnOGAhOGAueGAmeGAueGAmeGAuuGArOGAuOGAkOGAvOGAhOGAuSDhgIDhgK3hgJThgLnhgLjhgLHhgKHhgKzhgIThgLnhgLjhgLHhgJThgLHhgJ7hgKwg4YCZ4YC94YCs4YC44YCa4YC84YCE4YC54YC44YCe4YCK4YC54YC34YCh4YCa4YCw4YCh4YCG4YCZ4YC64YCs4YC4', '4pyUICBGaWxlIFNpemU6IDYuMTUgTUI=', '4pyUIOGAu+GAleGAlOGAueGAhuGAreGAr+GAnuGAsC0g4YCx4YCZ4YCs4YC54YCc4YCd4YCuIOGAoeGAl+GAsOGAh+GAluGAm+GAueGAoeGAnOGAruGAm+GAveGArOGAuOGAn+GAuS3hgKXhgK7hgLjhgLHhgJnhgKzhgIThgLnhgLvhgJbhgK3hgLPhgLg='),
(3, 'https://androlover.com/islamic/images/img3.jpg', 'https://androlover.com/islamic/books/B3.pdf', 'IB3.pdf', '4pyUICDhgLHhgIfhgJrhgKzhgJvhgJ7hgLkg4YCh4YCu4YCF4YCs4YCx4YCc4YCF4YCd4YCr4YC44YCX4YC54YKP4YC94YCE4YC54YC3IOGAkuGAreGAr+GAoeGArOGAmeGAuuGArOGAuA==', '4pyUICBGaWxlIFNpemU6IDIuNTYgTUI=', '4pyUIFJlZnVyYmlzaGVkIFNjYW4gQm9vaw=='),
(4, 'https://androlover.com/islamic/images/img4.jpg', 'https://androlover.com/islamic/books/B4.pdf', 'IB4.pdf', '4pyUIOGAmeGAvOGAkOGAueGAheGAnOGAhOGAueGAmeGAueGAn+GAsOGAnuGAiuGAuSDhgKHhgJjhgJrhgLnhgJThgIrhgLnhgLg=', '4pyUIEZpbGUgU2l6ZTogNzQ1IEtC', '4pyUIOGAu+GAleGAs+GAheGAr+GAnuGAsDog4YCC4YC64YCs4YGA4YCt4YCS4YC54YCe4YCU4YC54YC4'),
(5, 'https://androlover.com/islamic/images/img5.jpg', 'https://androlover.com/islamic/books/B5.pdf', 'IB5.pdf', '4pyUIOGAlOGAreGAgOGArOGAn+GAueGAhuGAreGAr+GAr+GAkOGArOGAmOGArOGAnOGAsg==', '4pyUIEZpbGUgU2l6ZTogNTI5IEtC', '4pyUIOGAu+GAleGAs+GAheGAr+GAnuGAsDog4YCx4YCZ4YCs4YC54YCc4YCs4YCU4YCsIOGAoeGAruGAheGArCAo4YCV4YCy4YC84YKP4YC84YCa4YC54YCA4YCv4YCU4YC54YC4KQ=='),
(6, 'https://androlover.com/islamic/images/img6.jpg', 'https://androlover.com/islamic/books/B6.pdf', 'IB6.pdf', '4pyUIOGAmeGAseGAnuGAgeGAhOGAueGAmOGArOGAnOGAr+GAleGAueGAnuGAhOGAueGAt+GAnuGAnOGAsg==', '4pyUIEZpbGUgU2l6ZTogMi41MCBNQg==', '4pyUIOGAu+GAleGAlOGAueGAhuGAreGAr+GAseGAm+GAuOGAnuGArOGAuOGAnuGAsDog4YCx4YCZ4YCs4YC54YCc4YCs4YCU4YCsIOGAn+GArOKAi+GAluGAvOGAh+GAuSDhgIDhgKzhgJvhgK4g4YCZ4YCv4YCf4YCZ4YG84YCS4YC5IOGAoeGAnOGArg=='),
(7, 'https://androlover.com/islamic/images/img7.jpg', 'https://androlover.com/islamic/books/B7.pdf', 'IB7.pdf', '4pyUIOGAoeGAmOGAmuGAueGAt+GAseGBvuGAgOGArOGAhOGAueGAtyDhgILhgLrhgJnhgKzhgKHhgJDhgLnhgJHhgLzhgIDhgLnhgJvhgJ7hgJThgIrhgLnhgLg=', '4pyUIEZpbGUgU2l6ZTogMS4zOCBNQg==', '4pyUIOGAu+GAleGAs+GAheGAr+GAnuGAsDog4YCh4YCX4YC54YCS4YC84YCb4YC54YCb4YCb4YC94YCu4YC44YCS4YC5IOGAn+GAleGAueGAgOGArOGAlOGAruGAuA=='),
(8, 'https://androlover.com/islamic/images/img8.jpg', 'https://androlover.com/islamic/books/B8.pdf', 'IB8.pdf', '4pyUIOGAn+GAguGAuuGAueGAhuGAreGAr+GAkOGArOGAmOGArOGAnOGAsg==', '4pyUIEZpbGUgU2l6ZTogMS4zNyBNQg==', '4pyUIFJlZnVyYmlzaGVkIFNjYW4gQm9vaw=='),
(9, 'https://androlover.com/islamic/images/img9.jpg', 'https://androlover.com/islamic/books/B9.pdf', 'IB9.pdf', '4pyUIOGBh+GBiOGBhiDhgIbhgK3hgK/hgK/hgJDhgKzhgJjhgKzhgJzhgLI=', '4pyUIEZpbGUgU2l6ZTogMS45NCBNQg==', '4pyUIOGAu+GAleGAs+GAheGAr+GAnuGAsDog4YCF4YCt4YCU4YC54YCx4YCM4YC44YCf4YCU4YC5'),
(10, 'https://androlover.com/islamic/images/img10.jpg', 'https://androlover.com/islamic/books/B10.pdf', 'IB10.pdf', '4pyUIOGAheGAsOGAm+GArOGAmeGAuuGArOGAuOGBjyDhgKHhgIDhgLrhgLPhgK3hgLjhgKHhgKzhgJThgK3hgJ7hgIThgLk=', '4pyUIEZpbGUgU2l6ZTogMS4zNyBNQg==', '4pyUIOGAheGAruGAheGApeGAueGAseGAm+GAuOGAnuGArOGAuOGAnuGAsDogQy5BLiDhgKXhgK7hgLjhgJfhgJzhgLzhgIThgLk='),
(11, 'https://androlover.com/islamic/images/img11.jpg', 'https://androlover.com/islamic/books/B11.pdf', 'IB11.pdf', '4pyUIOGAn+GAkuGAruGAuOGAhuGAueGBvuGAnuGAneGAq+GAkuGAseGAkOGArOGAuSDhgLHhgJzhgLjhgIbhgJrhgLnhgY/hgJHhgLDhgLjhgLvhgJnhgJDhgLnhgJnhgojhgo/hgL3hgIThgLnhgLfhgKHhgJPhgK3hgJXhgbjhgKzhgJrhgLk=', '4pyUIEZpbGUgU2l6ZTogMS4wMSBNQg==', '4pyUIOGAu+GAleGAs+GAheGAr+GAnuGAsDog4YCZ4YCS4YC54YCb4YCF4YCf4YC5IOGAoeGAm+GAl+GAreGAmuGAn+GAuSDhgIXhgK3hgK/hgJzhgK3hgK/hgIThgLnhgJnhgKzhgJThgK3hgJrhgJ/hgLk='),
(12, 'https://androlover.com/islamic/images/img12.jpg', 'https://androlover.com/islamic/books/B12.pdf', 'IB12.pdf', '4pyUIOGAluGAh+GArOGAseGAoeGAseGAnOGAoeGAoeGAueGAmeGArOGAnOGAueGAseGAleGAq+GAhOGAueGAuOGAgeGAuuGAs+GAleGAueGBjyDhgIHhgIDhgLnhgIbhgIXhgLnhgKHhgJjhgK3hgJPhgKzhgJThgLk=', '4pyUIEZpbGUgU2l6ZTogNC4wMyBNQg==', '4pyUIOGAu+GAleGAs+GAheGAr+GAnuGAsDog4YCZ4YCv4YCW4YC54YCe4YCuIOGAmeGAr+GAn+GAmeGBvOGAkuGAuSDhgJvhgKzhgJvhgL3hgIXhgLnhgJLhgLkgKOGAl+GAreGAr+GAnOGAlOGAueGAkuGAueGAm+GAveGAsuGAn+GAueGAm+GArik='),
(13, 'https://androlover.com/islamic/images/img13.jpg', 'https://androlover.com/islamic/books/B13.pdf', 'IB13.pdf', '4pyUIOGAgOGAr+GAm+GAueGAoeGArOGAlOGAueGAgOGAreGAryDhgJ7hgLHhgJjhgKzhgLHhgJXhgKvhgIDhgLnhgJThgKzhgLjhgJzhgIrhgLnhgIXhgLzhgKwg4YCb4YC84YCQ4YC54YCW4YCQ4YC54YCY4YCt4YCv4YKUIOGAnOGAreGAr+GAoeGAleGAueGAleGAq+GAnuGAnOGArOGAuA==', '4pyUIEZpbGUgU2l6ZTogODIwIEtC', '4pyUIOGAu+GAleGAlOGAueGAhuGAreGAr+GAnuGAsDog4YCx4YCZ4YCs4YCE4YC54YC74YCV4YCQ4YC54YCe4YCs4YC4'),
(14, 'https://androlover.com/islamic/images/img14.jpg', 'https://androlover.com/islamic/books/B14.pdf', 'IB14.pdf', '4pyUIOGAoeGAvOGAmeGBvOGAm+GAn+GAuSDhgJ/hgILhgLrhgLkg4YCZ4YCQ4YC54YCF4YC54YCC4YC64YCt4YCS4YCtIOGAlOGAl+GBgOGAriDhgIfhgK3hgJrhgKzhgJvhgJ7hgLkg4YCc4YCZ4YC54YC44YCK4YKK4YCU4YC5', '4pyUIEZpbGUgU2l6ZTogMC45OCBNQg==', '4pyUIOGAu+GAleGAlOGAueGAhuGAreGAr+GAnuGAsDog4YCh4YCc4YC54YCf4YCC4YC64YC5IOGApuGAuOGAnOGAveGAseGAm+GCiiA='),
(15, 'https://androlover.com/islamic/images/img15.jpg', 'https://androlover.com/islamic/books/B15.pdf', 'IB15.pdf', '4pyUIOGAu+GAluGAheGAueGAm+GAleGAueGAmeGAveGAlOGAueGCj+GAveGAhOGAueGAtyDhgJXhgIrhgKzhgLHhgJXhgLgg4YCV4YC24YCv4YC74YCV4YCE4YC54YCZ4YC64YCs4YC4', '4pyUIEZpbGUgU2l6ZTogMi45OSBNQg==', '4pyUIOGAheGAruGAheGApeGAueGAnuGAsDog4YCx4YCZ4YCs4YC54YCc4YCs4YCU4YCsIOGAmeGAr+GAn+GAmeGBvOGAkuGAuSDhgJ7hgLzhgKzhgJ/hgK3hgJvhgLkg'),
(16, 'https://androlover.com/islamic/images/img16.jpg', 'https://androlover.com/islamic/books/B16.pdf', 'IB16.pdf', '4pyUIOGApOGAgOGArOGAuOGAnuGAhOGAueGAt+GAgOGAtuGBvuGAgOGAmeGBvOGArOGAkOGAiuGAueGAuA==', '4pyUIEZpbGUgU2l6ZTogMS42OCBNQg==', '4pyUIOGAu+GAleGAs+GAheGAr+GAnuGAsDog4YCx4YCZ4YCs4YC54YCc4YCs4YCU4YCsIOGAgOGAmeGBvOGAm+GAvOGAkOGAueGAkuGAruGAuOGAlOGAuSDhgKXhgK7hgLjhgJ7hgJThgLnhgLjhgLHhgJnhgKzhgIThgLk='),
(17, 'https://androlover.com/islamic/images/img17.jpg', 'https://androlover.com/islamic/books/B17.pdf', 'IB17.pdf', '4pyUIOGAmeGAveGAkOGAueGAluGAvOGAmuGAuSDhgKHhgJzhgK7hgJzhgK4=', '4pyUIEZpbGUgU2l6ZTogMS42MCBNQg==', '4pyUIOGAu+GAleGAlOGAueGAhuGAreGAr+GAnuGAsDog4YCx4YCZ4YCs4YC54YCc4YCs4YCU4YCsIOGAn+GAl+GAruGAl+GAvOGAkuGAueGAkuGAruGAuOGAlOGAuQ=='),
(18, 'https://androlover.com/islamic/images/img18.jpg', 'https://androlover.com/islamic/books/B18.pdf', 'IB18.pdf', '4pyUIOGAgOGAuuGAmeGAueGAuOGAu+GAmeGAkOGAueGAgOGAr+GAm+GAueGAoeGArOGAlOGAueGBj+GAseGAgOGAuuGArOGAgOGAueGAmeGAuuGAgOGAueGAm+GAkOGAlOGArOGAmeGAuuGArOGAuA==', '4pyUIEZpbGUgU2l6ZTogNS43NSBNQg==', '4pyUIOGAu+GAleGAs+GAheGAr+GAnuGAsDog4YCh4YCt4YCZ4YCs4YCZ4YC5IOGAguGAh+GArOGAnOGArg=='),
(19, 'https://androlover.com/islamic/images/img19.jpg', 'https://androlover.com/islamic/books/B19.pdf', 'IB19.pdf', '4pyUIOGAnuGArOGAuOGAnuGAmeGAruGAuOGAseGAgOGArOGAhOGAueGAuOGAu+GAluGAheGAueGAnOGAreGAr+GAseGAnuGArOGAuQ==', '4pyUIEZpbGUgU2l6ZTogMy41MyBNQg==', '4pyUIOGAu+GAleGAlOGAueGAhuGAreGAr+GAnuGAsDog4YCx4YCZ4YCs4YC54YCc4YCs4YCU4YCsIOGAmeGAr+GAluGAueGAnuGAriDhgIDhgKzhgJvhgK4g4YCZ4YCv4YCf4YCZ4YG84YCS4YC5IOGAn+GAlOGAueGAh+GAvOGAnOGAn+GAuQ=='),
(20, 'https://androlover.com/islamic/images/img20.jpg', 'https://androlover.com/islamic/books/B20.pdf', 'IB20.pdf', '4pyUIOGAnuGAoeGAueGAnOGAruGAmeGAvOGAnOGAueGAgOGAr+GAm+GAueGAoeGArOGAlOGAuQ==', '4pyUIEZpbGUgU2l6ZTogNC4xNCBNQg==', '4pyUIOGAu+GAleGAs+GAheGAr+GAnuGAsDogTWVkaWEgU21hcnQ='),
(21, 'https://androlover.com/islamic/images/img21.jpg', 'https://androlover.com/islamic/books/B21.pdf', 'IB21.pdf', '4pyUIOGAkOGAgOGBoOGAnOGAreGAkuGAueGAnuGAiuGAuSDhgJbhgJvhgKzhgIfhgLk=', '4pyUIEZpbGUgU2l6ZTogNS4yNiBNQg==', '4pyUIOGAu+GAleGAs+GAheGAr+GAnuGAsDog4YCx4YCZ4YCs4YC54YCc4YCd4YCuIOGAleGAnuGAruGAseGAgOGAuuGArOGAueGApeGAruGAuA=='),
(22, 'https://androlover.com/islamic/images/img22.jpg', 'https://androlover.com/islamic/books/B22.pdf', 'IB22.pdf', '4pyUIOGAnuGAn+GAguGAuuGAueGAguGBveGAvOGAkuGAuSDhgJThgJnhgKzhgIfhgLk=', '4pyUIEZpbGUgU2l6ZTogMy42MSBNQg==', '4pyUIOGAu+GAleGAlOGAueGAhuGAreGAr+GAnuGAsDog4YCx4YCZ4YCs4YC54YCc4YCs4YCU4YCsIOGAgOGArOGAm+GAriDhgJnhgK/hgJ/hgJnhgbzhgJLhgLkg4YCa4YCw4YKP4YC84YCQ4YC54YCF4YC5'),
(23, 'https://androlover.com/islamic/images/img23.jpg', 'https://androlover.com/islamic/books/B23.pdf', 'IB23.pdf', '4pyUIOGAseGAluGAvOGAgOGAn+GAueGAu+GAluGAheGAueGAseGAleGBmuGAluGAvOGAtuGClOGAu+GAluGAreGAs+GAuOGAkOGAreGAr+GAuOGAkOGAgOGAueGAnOGArOGAleGAtuGAr+GAnuGAmeGAreGAr+GAhOGAueGAuA==', '4pyUIEZpbGUgU2l6ZTogNi40MCBNQg==', '4pyUIOGAu+GAleGAlOGAueGAhuGAreGAr+GAnuGAsDog4YCl4YCu4YC44YCx4YCA4YC64YCs4YC54YCG4YCU4YC54YC4ICjhgJnhgo/hgbHhgLHhgJzhgLgp'),
(24, 'https://androlover.com/islamic/images/img24.jpg', 'https://androlover.com/islamic/books/B24.pdf', 'IB24.pdf', '4pyUIOGAkOGAl+GAueGAnOGAruGAuOGAguGAueGAseGAleGAq+GAhOGAueGAuOGAgeGAuuGAs+GAleGAueGAgOGAuuGAmeGAueGAuA==', '4pyUIEZpbGUgU2l6ZTogMjkuNiBNQg==', '4pyUIOGAu+GAleGAlOGAueGAhuGAreGAr+GAnuGAsDog4YCh4YCc4YC54YCf4YCC4YC64YC5IOGAseGAmeGArOGAueGAnOGArOGAlOGArCDhgJnhgK/hgJ/hgJnhgbzhgJLhgLkg4YCZ4YCw4YCF4YCs'),
(25, 'https://androlover.com/islamic/images/img25.jpg', 'https://androlover.com/islamic/books/B25.pdf', 'IB25.pdf', '4pyUIOGAseGAnuGArOGAhOGAueGAn+GAruGAuOGAkuGAuSA=', '4pyUIEZpbGUgU2l6ZTogNTIxIEtC', '4pyUIOGAu+GAleGAs+GAheGAr+GAnuGAsDog4YCx4YCZ4YCs4YC54YCc4YCs4YCU4YCsIOGAoeGAl+GBuuGAkuGAvOGAnOGAueGAgOGArOGAkuGAreGAm+GAuQ=='),
(26, 'https://androlover.com/islamic/images/img26.jpg', 'https://androlover.com/islamic/books/B26.pdf', 'IB26.pdf', '4pyUIOGAm+GAnuGAmeGAsuGAtyDhgKHhgIDhgK/hgJ7hgK3hgK/hgJzhgLk=', '4pyUIEZpbGUgU2l6ZTogMi43NCBNQg==', '4pyUIOGAu+GAleGAlOGAueGAhuGAreGAr+GAnuGAsDog4YCx4YCZ4YCs4YC54YCc4YCd4YCuIOGAn+GAl+GAruGAl+GAr+GAnOGAueGAnOGArOGAn+GAuSAo4YCZ4YCf4YC54YCZ4YCw4YCS4YCuKQ=='),
(27, 'https://androlover.com/islamic/images/img27.jpg', 'https://androlover.com/islamic/books/B27.pdf', 'IB27.pdf', '4pyUIOGAnuGAguGAuuGAueGAneGAruGAuOGAkuGAuQ==', '4pyUIEZpbGUgU2l6ZTogMzM3IEtC', '4pyUIOGAkOGAhOGAueGAu+GAleGAnuGAsDog4YCh4YCc4YC54YCf4YCC4YC64YC5IOGAseGAmeGArOGAueGAnOGArOGAlOGArCDhgJ/hgKzigIvhgJbhgLzhgIfhgLkg4YCh4YCX4YG64YCS4YC84YCc4YC54YCA4YCs4YCS4YCt4YCb4YC5'),
(28, 'https://androlover.com/islamic/images/img28.jpg', 'https://androlover.com/islamic/books/B28.pdf', 'IB28.pdf', '4pyUIOGAnuGAguGAuuGAueGAneGAruGAuOGAkuGAuSDhgIDhgK/hgJvhgLnhgKHhgKzhgJThgLnhgIDhgLrhgJnhgLnhgLjhgLvhgJnhgJDhgLkg4YCb4YC84YCQ4YC54YCW4YCQ4YC54YCU4YCK4YC54YC44YCc4YCZ4YC54YC44YCK4YKK4YCU4YC5', '4pyUIEZpbGUgU2l6ZTogNS4wMSBNQg==', '4pyUIOGAu+GAleGAs+GAheGAr+GAnuGAsDog4YC74YCE4YCt4YCZ4YC54YC44YCB4YC64YCZ4YC54YC44YCc4YCv4YCc4YCE4YC5ICjhgKHhgJzhgLnhgJ/hgILhgLrhgLkg4YCZ4YCv4YCW4YC54YCe4YCuIOGApeGAruGAuOGAu+GAmeGAhOGAueGAt+GAnuGAreGAlOGAueGAuCk='),
(29, 'https://androlover.com/islamic/images/img29.jpg', 'https://androlover.com/islamic/books/B29.pdf', 'IB29.pdf', '4pyUIOGAhuGAvOGArOGAnOGAreGAn+GArOGAnuGAuSDhgo/hgL3hgIThgLnhgLcg4YCZ4YCt4YCe4YCs4YC44YCF4YCv4YCx4YG+4YCA4YC44YCZ4YC24YCv', '4pyUIEZpbGUgU2l6ZTogNi40NiBNQg==', '4pyUIOGAu+GAleGAs+GAheGAr+GAnuGAsDog4YCx4YCZ4YCs4YC54YCc4YCs4YCU4YCsIOGAn+GArOKAi+GAluGAvOGAh+GAuSDhgKHhgJfhgbrhgJLhgLzhgJzhgLnhgIDhgKzhgJLhgK3hgJvhgLk='),
(30, 'https://androlover.com/islamic/images/img30.jpg', 'https://androlover.com/islamic/books/B30.pdf', 'IB30.pdf', '4pyUIOGAheGAvOGAnOGArOGAnuGAuSDhgLHhgIHhgZog4YCU4YCZ4YCs4YCH4YC5', '4pyUIEZpbGUgU2l6ZTogNS44NyBNQg==', '4pyUIOGAheGAruGAheGApeGAueGAseGAm+GAuOGAnuGArOGAuOGAnuGAsDog4YCx4YCZ4YCs4YC54YCc4YCs4YCU4YCsIOGCj+GAsOGAuOGAm+GAueGAmeGAr+GAn+GAmeGBvOGAkuGAuQ=='),
(31, 'https://androlover.com/islamic/images/img31.jpg', 'https://androlover.com/islamic/books/B31.pdf', 'IB31.pdf', '4pyUIOGAheGAsOGAm+GAn+GAuSDhgJrhgKzhgIXhgK7hgLjhgJThgLnhgo/hgL3hgIThgLfhgLkg4YCF4YCw4YCb4YCf4YC5KOGBgeGBgCnhgJXhgK/hgJLhgLkgKOGAoeGAm+GAl+GAri3hgLvhgJnhgJThgLnhgJnhgKwg4YCh4YCe4YC24YCR4YC84YCA4YC5KQ==', '4pyUIEZpbGUgU2l6ZTogMS43OSBNQg==', '4pyUIOGAu+GAleGAs+GAheGAr+GAnuGAsDog4YCD4YCs4YCH4YCuIOGAseGAmeGArOGAueGAnOGAneGAriBLLkIg4YCF4YCt4YCv4YC44YCc4YC84YCE4YC5ICjhgJnhgJ/hgLnhgJnhgLDhgJLhgK4p'),
(32, 'https://androlover.com/islamic/images/img32.jpg', 'https://androlover.com/islamic/books/B32.pdf', 'IB32.pdf', '4pyUIOGAseGCj+GAvOGAm+GArOGAnuGAruGCj+GAveGAhOGAueGAtyDhgIDhgLzhgb3hgo/hgK/hgLnhgJXhgLnhgJDhgK3hgK/hgpThgY8g4YCW4YCC4YC64YCb4YC54YCU4YCZ4YCs4YCH4YC5', '4pyUIEZpbGUgU2l6ZTogNTUwIEtC', '4pyUIFJlZnVyYmlzaGVkIFNjYW4gQXJ0aWNsZQ=='),
(33, 'https://androlover.com/islamic/images/img33.jpg', 'https://androlover.com/islamic/books/B33.pdf', 'IB33.pdf', '4pyUIOGAheGAreGAr+GAnOGAreGAr+GAhOGAueGAmeGAlOGAueGAlOGAl+GAruGCj+GAveGAhOGAueGAtyDhgJXhgK/hgJvhgLzhgIDhgLnhgIbhgK3hgJDhgLnhgKHhgLHhgb7hgIDhgKzhgIThgLnhgLgg4YCe4YCt4YCx4YCA4YCs4YCE4YC54YC44YCF4YCb4YCs4YCZ4YC64YCs4YC4', '4pyUIEZpbGUgU2l6ZTogMS4yMCBNQg==', '4pyUIOGAu+GAleGAs+GAheGAr+GAnuGAsDog4YCx4YCZ4YCs4YC54YCc4YCs4YCU4YCsIOGAn+GArOKAi+GAluGAvOGAh+GAuSDhgJnhgK/hgJ/hgJnhgbzhgJLhgLkg4YCh4YCu4YCF4YCs'),
(34, 'https://androlover.com/islamic/images/img34.jpg', 'https://androlover.com/islamic/books/B34.pdf', 'IB34.pdf', '4pyUIOGAkOGAmeGAlOGAueGAseGAkOGArOGAueGAu+GAmeGAkOGAuSjhgIbhgLwp4YGPIOGAheGAvOGAluGBueGAn+GAueGAseGAgOGAuuGArOGAhOGAueGAuOGAseGAkOGArOGAueGAnuGArOGAuOGAmeGAuuGArOGAuA==', '4pyUIEZpbGUgU2l6ZTogMi41NyBNQg==', '4pyUIOGAu+GAleGAlOGAueGAhuGAreGAr+GAnuGAsDog4YCx4YCZ4YCs4YC54YCc4YCs4YCU4YCsIOGAmeGAr+GAn+GAmeGBvOGAkuGAuSDhgKHhgIXhgLnhgJfhgJvhgKzhgJ/hgK7hgLjhgJnhgLkg'),
(35, 'https://androlover.com/islamic/images/img35.jpg', 'https://androlover.com/islamic/books/B35.pdf', 'IB35.pdf', '4pyUIOGAnuGAtuGAseGAneGAguGAm+GAmuGAsOGAluGAvOGAmuGAueGAm+GArCDhgLHhgJ7hgJDhgLzhgIThgLnhgLjhgJnhgL0g4YCA4YCt4YCv4YCa4YC54YCx4YCQ4YC84YKU4YC74YCW4YCF4YC54YCb4YCV4YC54YCZ4YC94YCU4YC54YCZ4YC64YCs4YC4', '4pyUIEZpbGUgU2l6ZTogMy43NiBNQg==', '4pyUIOGAu+GAleGAlOGAueGAhuGAreGAr+GAnuGAsDog4YCf4YCs4oCL4YCW4YC84YCH4YC5IOGAoeGAl+GAueGAkuGAr+GAnOGAueGAn+GAluGAruGAuOGAh+GAuQ=='),
(36, 'https://androlover.com/islamic/images/img36.jpg', 'https://androlover.com/islamic/books/B36.pdf', 'IB36.pdf', '4pyUIOGAm+GAruGAr+GAh+GArOGApeGAleGAr+GAnuGAueGBjyDhgKHhgIbhgIThgLnhgLfhgKHhgJDhgJThgLnhgLjhgJnhgLrhgKzhgLg=', '4pyUIEZpbGUgU2l6ZTogMS4wNCBNQg==', '4pyUIOGAu+GAleGAs+GAheGAr+GAnuGAsDog4YCZ4YCv4YCW4YC54YCe4YCuIOGCj+GAsOGAuOGAm+GAueGAmeGAr+GAn+GAmeGBvOGAkuGAuSAo4YCZ4YCH4YC84YCs4YCx4YCf4YCb4YCuKQ=='),
(37, 'https://androlover.com/islamic/images/img37.jpg', 'https://androlover.com/islamic/books/B37.pdf', 'IB37.pdf', '4pyUIOGAheGAtuGAu+GAleGAmeGAreGAmOGCj+GAveGAhOGAueGAtyDhgJvhgIThgLnhgLHhgJ7hgLzhgLjhgJvhgJDhgJThgKw=', '4pyUIEZpbGUgU2l6ZTogMy4yMSBNQg==', '4pyUIOGAu+GAleGAs+GAheGAr+GAkOGAhOGAueGAu+GAleGAnuGAsDog4YCx4YCZ4YCs4YC54YCc4YCs4YCU4YCsIOGAn+GArOKAi+GAluGAvOGAh+GAuSDhgKHhgJfhgbrhgJLhgLzhgJzhgLnhgIDhgKzhgJLhgK3hgJvhgLkg'),
(38, 'https://androlover.com/islamic/images/img38.jpg', 'https://androlover.com/islamic/books/B38.pdf', 'IB38.pdf', '4pyUIOGAu+GAmeGAkOGAueGAlOGAl+GAruGBjyDhgIXhgLbhgLvhgJXhgIDhgK3hgK/hgJrhgLnhgIDhgLrhgIThgLnhgLfhgJDhgJvhgKzhgLjhgJnhgLrhgKzhgLg=', '4pyUIEZpbGUgU2l6ZTogNS45NSBNQg==', '4pyUIOGAheGAruGAheGApeGAueGAnuGAsDog4YCf4YCs4YCC4YC64YCuIOGAmeGAr+GAn+GAmeGBvOGAkuGAuSDhgKHhgK/hgJnhgJvhgLkgKOGAgSkg4YCQ4YCE4YC54YCl4YCu4YC4'),
(39, 'https://androlover.com/islamic/images/img39.jpg', 'https://androlover.com/islamic/books/B39.pdf', 'IB39.pdf', '4pyUIOGAseGAm+GCiuGCj+GCiOGAkOGAueGCj+GAveGAnOGAtuGAr+GAuCDhgJHhgK3hgJThgLnhgLjhgJ7hgK3hgJnhgLnhgLjhgLHhgJvhgLjhgJDhgKzhgJ3hgJThgLk=', '4pyUIEZpbGUgU2l6ZTogNC4xMyBNQg==', '4pyUIOGAu+GAleGAlOGAueGAhuGAreGAr+GAnuGAsDog4YCx4YCZ4YCs4YC54YCc4YCs4YCU4YCsIOGAn+GArOKAi+GAluGAvOGAh+GAuSDhgKHhgJfhgbrhgJLhgLzhgJzhgLnhgIDhgKzhgJLhgK3hgJvhgLkg'),
(40, 'https://androlover.com/islamic/images/img40.jpg', 'https://androlover.com/islamic/books/B40.pdf', 'IB40.pdf', '4pyUIOGAgOGAuuGAhOGAueGAt+GAheGApeGAueGAkeGAsOGAuOGCj+GAveGAhOGAueGAtyDhgJbhgLDhgLjhgIXhgKzhgJvhgL3hgIThgLk=', '4pyUIEZpbGUgU2l6ZTogMy4zNCBNQg==', '4pyUIOGAu+GAleGAlOGAueGAhuGAreGAr+GAseGAm+GAuOGAnuGArOGAuOGAnuGAsDog4YCZ4YCv4YCW4YC54YCe4YCuIOGAn+GArOKAi+GAluGAvOGAh+GAuSDhgKHhgJfhgbrhgJLhgLzhgJvhgLnhgJvhgJ/hgK7hgLjhgJnhgLkg'),
(41, 'https://androlover.com/islamic/images/img41.jpg', 'https://androlover.com/islamic/books/B41.pdf', 'IB41.pdf', '4pyUIOGAseGAhuGAuOGAnOGAreGAleGAueGAseGAnuGArOGAgOGAueGAnuGAtuGAr+GAuOGAu+GAgeGAhOGAueGAuOGCj+GAveGAhOGAueGAtyDhgKHhgIXhgaXhgJzhgKzhgJnhgLnhgLfhgKHhgLvhgJnhgIThgLk=', '4pyUIEZpbGUgU2l6ZTogNzIzIEtC', '4pyUIOGAu+GAleGAs+GAheGAr+GAnuGAsDog4YCx4YCZ4YCs4YC54YCc4YCd4YCuIOGAmeGAr+GAn+GAmeGBvOGAkuGAuSDhgJDhgLzhgK3hgLPhgIThgLnhgJrhgIXhgLnhgJfhgLkgKOGAm+GAveGAmeGAueGAheGArik='),
(42, 'https://androlover.com/islamic/images/img42.jpg', 'https://androlover.com/islamic/books/B42.pdf', 'IB42.pdf', '4pyUIOGAkOGAmeGAlOGAueGAseGAkOGArOGAueGAu+GAmeGAkOGAueGBjyDhgKHhgLvhgJXhgLbhgLPhgLjhgJvhgK3hgJXhgLnhgLHhgJDhgKzhgLnhgJnhgLrhgKzhgLg=', '4pyUIEZpbGUgU2l6ZTogMy45MCBNQg==', '4pyUIOGAu+GAleGAlOGAueGAhuGAreGAr+GAnuGAsDog4YCx4YCZ4YCs4YC54YCc4YCs4YCU4YCsIOGAgOGArOGAm+GAriDhgJnhgK/hgJ/hgJnhgbzhgJLhgLkg4YCa4YCw4YKP4YC84YCQ4YC54YCF4YC5KOGAmeGAoeGAsOGAleGAhOGAuSk='),
(43, 'https://androlover.com/islamic/images/img43.jpg', 'https://androlover.com/islamic/books/B43.pdf', 'IB43.pdf', '4pyUIOGAseGAgOGAmuGArOGAmeGAnuGAueGBjyDhgJThgK3hgJnhgK3hgJDhgLnhgJzhgIDhgaHhgI/hgKzhgJnhgLrhgKzhgLg=', '4pyUIEZpbGUgU2l6ZTogMi4zNSBNQg==', '4pyUIOGAu+GAleGAlOGAueGAhuGAreGAr+GAnuGAsDog4YCx4YCZ4YCs4YC54YCc4YCs4YCU4YCsIOGAgOGArOGAm+GAriDhgJnhgK/hgJ/hgJnhgbzhgJLhgLkg4YCa4YCw4YKP4YC84YCQ4YC54YCF4YC5ICjhgJnhgKHhgLDhgJXhgIThgLkp'),
(44, 'https://androlover.com/islamic/images/img44.jpg', 'https://androlover.com/islamic/books/B44.pdf', 'IB44.pdf', '4pyUIOGAoeGAheGBpeGAnOGArOGAmeGAueGAnuGArOGAnuGAlOGArOGAseGAkOGArOGAueGBj+GAgOGAseGAnOGAmeGAn+GAuSAo4YGHKeGAleGAr+GAkuGAuQ==', '4pyUIEZpbGUgU2l6ZTogNzk5IEtC', '4pyUIFJlZnVyYmlzaGVkIFNjYW4gQXJ0aWNsZQ=='),
(45, 'https://androlover.com/islamic/images/img45.jpg', 'https://androlover.com/islamic/books/B45.pdf', 'IB45.pdf', '4pyUIOGAn+GAkuGAruGAuOGAhuGAueGAseGAkOGArCDhgLnhgKHhgJDhgK3hgK/hgK/hgLHhgJzhgLjhgIbhgJrhgLnhgo/hgL3hgIThgLnhgLcg4YCh4YCb4YC94YCK4YC54YKP4YC94YCF4YC54YCG4YCa4YC5', '4pyUIEZpbGUgU2l6ZTogMzM1IEtC', '4pyUIOGAu+GAleGAs+GAheGAr+GAnuGAsDog4YCh4YCt4YCv4YCc4YCZ4YCsIOGAoeGAheGBpeGAnOGArOGAmeGAuSDhgJ7hgKzhgJ7hgJThgKzhgLfhgJXhgIrhgKzhgJvhgL3hgIThgLnhgJnhgLrhgKzhgLgg4YCh4YCW4YC84YCy4YKU4YCB4YC64YCz4YCV4YC5'),
(46, 'https://androlover.com/islamic/images/img46.jpg', 'https://androlover.com/islamic/books/B46.pdf', 'IB46.pdf', '4pyUIOGAoeGAseGAmeGAuOGAm+GAveGAreGAnOGArCDhgJHhgK3hgK/hgKHhgIHhgKs=', '4pyUIEZpbGUgU2l6ZTogNC45MiBNQg==', '4pyUIOGAu+GAleGAs+GAheGAr+GAnuGAsDog4YCF4YCt4YCU4YC54YCx4YCM4YC44YCf4YCU4YC5'),
(47, 'https://androlover.com/islamic/images/img47.jpg', 'https://androlover.com/islamic/books/B47.pdf', 'IB47.pdf', '4pyUIOGAoeGAnOGCheGArOGAn+GAueGAoeGAm+GAveGAhOGAueGAu+GAmeGAkOGAueGAkeGAtiDhgIHhgK3hgK/hgJzhgLbhgojhgLvhgIHhgIThgLnhgLg=', '4pyUIEZpbGUgU2l6ZTogMi45NSBNQg==', '4pyUIOGAu+GAleGAs+GAheGAr+GAnuGAsDog4YCf4YCH4YC54YCb4YCe4YC5IOGAseGAmeGArOGAueGAnOGArOGAlOGArCDhgKHhgIXhgLnhgIDhgLnhgJjhgKzhgLjhgJzhgLnhgJjhgKzhgJ3hgKvhgLg='),
(48, 'https://androlover.com/islamic/images/img48.jpg', 'https://androlover.com/islamic/books/B48.pdf', 'IB48.pdf', '4pyUIOGAnOGAreGAveGAuuGAs+GCleGBgOGAveGAgOGAueGAm+GAkOGAlOGArOGAnuGAreGAr+GAgOGAuQ==', '4pyUIEZpbGUgU2l6ZTogMi4yMyBNQg==', '4pyUIOGAu+GAleGAs+GAheGAr+GAnuGAsDog4YCx4YCZ4YCs4YC54YCc4YCs4YCU4YCsIOGAmeGAr+GAluGAueGAnuGAriDhgJnhgK/hgJ/hgJnhgbzhgJLhgLkg4YCh4YCb4YC94YC54YCb4YCW4YC5IA=='),
(49, 'https://androlover.com/islamic/images/img49.jpg', 'https://androlover.com/islamic/books/B49.pdf', 'IB49.pdf', '4pyUIOGAlOGAmeGArOGAh+GAueGBjyDhgJzhgLrhgLPhgK3hgpXhgJ3hgL3hgIDhgLnhgIHhgLrhgIDhgLnhgJnhgLrhgKzhgLg=', '4pyUIEZpbGUgU2l6ZTogMi42MiBNQg==', '4pyUIOGAkOGAhOGAueGAu+GAleGAnuGAsDog4YCZ4YCv4YCW4YC54YCe4YCuIOGAoeGAvOGAkOGAueGAheGAueGAmeGArOGAuOGAlOGAuQ=='),
(50, 'https://androlover.com/islamic/images/img50.jpg', 'https://androlover.com/islamic/books/B50.pdf', 'IB50.pdf', '4pyUIOGAu+GAmeGAlOGAueGAmeGArOGAt+GAoeGArOGAh+GArOGAlOGAiuGAueGAseGAgeGAq+GAhOGAueGAuOGAseGAhuGArOGAhOGAuSDhgIbhgJvhgKzhgb7hgIDhgK7hgLjhgKbhgLjhgJvhgKzhgIfhgJDhgLk=', '4pyUIEZpbGUgU2l6ZTogMzIuMiBNQg==', '4pyUIOGAu+GAleGAs+GAheGAr+GAnuGAsDog4YCd4YCZ4YC54YC44YCh4YCt4YCv4YCd4YCZ4YC54YC44YCx4YCA4YC64YCs4YC54YCd4YCE4YC54YC44YCx4YCZ4YCs4YCE4YC5'),
(51, 'https://androlover.com/islamic/images/img51.jpg', 'https://androlover.com/islamic/books/B51.pdf', 'IB51.pdf', '4pyUIOGAoeGAheGAvOGAmeGAueGAuOGAkeGAgOGAueGAnuGAiuGAueGAtyDhgIXhgJnhgLbhgK/hgJThgIDhgLk=', '4pyUIEZpbGUgU2l6ZTogMi41NSBNQg==', '4pyUIOGAu+GAleGAlOGAueGAhuGAreGAr+GAnuGAsDog4YCx4YCZ4YCs4YC54YCc4YCs4YCU4YCsIOGAmeGAr+GAn+GAmeGBvOGAkuGAuSDhgKHhgIXhgLnhgJfhgJvhgKzhgJ/hgK7hgLjhgJnhgLk='),
(52, 'https://androlover.com/islamic/images/img52.jpg', 'https://androlover.com/islamic/books/B52.pdf', 'IB52.pdf', '4pyUIOGAh+GAgOGArOGAuOGAnuGAueGAhuGAreGAr+GAhOGAueGAm+GArCDhgJThgIrhgLnhgLjhgKXhgJXhgLHhgJIg4YC74YCV4YCM4YCs4YCU4YC54YC44YCB4YC64YCA4YC54YCZ4YC64YCs4YC4', '4pyUIEZpbGUgU2l6ZTogMTQuNCBNQg==', '4pyUIOGAu+GAleGAs+GAheGAr+GAnuGAsDog4YCx4YCZ4YCs4YC54YCc4YCs4YCU4YCsIOGAmeGAr+GAluGAueGAnuGAriDhgJnhgK/hgJ/hgJnhgbzhgJLhgLkg4YCb4YCW4YC54YCh4YCe4YC5'),
(53, 'https://androlover.com/islamic/images/img53.jpg', 'https://androlover.com/islamic/books/B53.pdf', 'IB53.pdf', '4pyUIOGCkOGAr+GAreGAh+GArOGBj+GAleGAiuGAkOGAueGAgeGAuuGAgOGAueGAmeGAuuGArOGAuA==', '4pyUIEZpbGUgU2l6ZTogMi4zNSBNQg==', '4pyUIOGAu+GAleGAlOGAueGAhuGAreGAr+GAnuGAsDog4YCx4YCZ4YCs4YC54YCc4YCd4YCuIOGAn+GArOKAi+GAluGAvOGAh+GAuSDhgJnhgK/hgJ/hgJnhgbzhgJLhgLkg4YCZ4YCs4YCZ4YC54YCG4YCs'),
(54, 'https://androlover.com/islamic/images/img54.jpg', 'https://androlover.com/islamic/books/B54.pdf', 'IB54.pdf', '4pyUIOGAlOGAmeGArOGAh+GAueGAhuGAreGAr+GAhOGAueGAm+GArCDhgJPhgJnhgbzhgJ7hgJDhgLnhgIDhgLrhgJnhgLnhgLggKOGBgSk=', '4pyUIEZpbGUgU2l6ZTogNy4zNyBNQg==', '4pyUIOGAu+GAleGAlOGAueGAhuGAreGAr+GAnuGAsDog4YCx4YCZ4YCs4YC54YCc4YCd4YCuIOGAn+GAl+GAruGAl+GAr+GAnOGAueGAnOGArOGAn+GAuQ=='),
(55, 'https://androlover.com/islamic/images/img55.jpg', 'https://androlover.com/islamic/books/B55.pdf', 'IB55.pdf', '4pyUIOGAlOGAmeGArOGAh+GAueGAhuGAreGAr+GAhOGAueGAm+GArCDhgJPhgJnhgbzhgJ7hgJDhgLnhgIDhgLrhgJnhgLnhgLggKOGBgik=', '4pyUIEZpbGUgU2l6ZTogNS42MCBNQg==', '4pyUIOGAu+GAleGAlOGAueGAhuGAreGAr+GAnuGAsDog4YCx4YCZ4YCs4YC54YCc4YCd4YCuIOGAn+GAl+GAruGAl+GAr+GAnOGAueGAnOGArOGAn+GAuSAo4YCZ4YCf4YC54YCZ4YCw4YCS4YCuKQ=='),
(56, 'https://androlover.com/islamic/images/img56.jpg', 'https://androlover.com/islamic/books/B56.pdf', 'IB56.pdf', '4pyUIOGAl+GAnOGAruGBgOGAkOGAueGAseGAgOGAuuGArOGAhOGAueGAuOGAseGAkOGArOGAueGAhuGAreGAr+GAhOGAueGAm+GArCDhgIXhgIrhgLnhgLjhgJnhgLrhgKXhgLnhgLjhgIXhgIrhgLnhgLjhgIDhgJnhgLnhgLjhgIHhgLrhgIDhgLnhgJnhgLrhgKzhgLg=', '4pyUIEZpbGUgU2l6ZTogMi40MSBNQg==', '4pyUIOGAu+GAleGAlOGAueGAhuGAreGAr+GAnuGAsDog4YCD4YCs4YCH4YCuIOGAseGAmeGArOGAueGAnOGAneGAriDhgIDhgJvhgK7hgLjhgJnhgLnhgJjhgIHhgLnhgJvhgL3hgLkg4YCl4YCu4YC44YCF4YCt4YCv4YC44YCc4YC84YCE4YC5'),
(57, 'https://androlover.com/islamic/images/img57.jpg', 'https://androlover.com/islamic/books/B57.pdf', 'IB57.pdf', '4pyUIOGAnOGBvuGAgOGAiuGAueGAt+GAu+GAgeGAhOGAueGAuOGCj+GAveGAhOGAueGAt+GAhuGAreGAr+GAhOGAueGAseGAnuGArOGAoeGAmeGAreGAlOGAueGClOGAseGAkOGArOGAueGAmeGAuuGArOGAuOGCj+GAveGAhOGAueGAt+GAleGAiuGAkOGAueGAgeGAuuGAgOGAueGAmeGAuuGArOGAuA==', '4pyUIEZpbGUgU2l6ZTogMy43NiBNQg==', '4pyUIOGAu+GAleGAs+GAheGAr+GAnuGAsDog4YCh4YCc4YC54YCf4YCC4YC64YC5IOGAseGAmeGArOGAueGAnOGArOGAlOGArCDhgJnhgK/hgJ/hgJnhgbzhgJLhgLkg4YCh4YCA4YC54YCY4YCb4YC54YCb4YC94YCs4YC4IA=='),
(58, 'https://androlover.com/islamic/images/img58.jpg', 'https://androlover.com/islamic/books/B58.pdf', 'IB58.pdf', '4pyUIOGAmeGAvOGAkOGAueGAheGAueGAnuGAlOGAkuGAuSDhgJvhgLDhgJ/hgKzhgJThgK7hgLHhgIbhgLjhgJThgIrhgLnhgLjhgLHhgJXhgKvhgIThgLnhgLgg4YGB4YGE4YGA', '4pyUIEZpbGUgU2l6ZTogMy4xOSBNQg==', '4pyUIOGAu+GAleGAlOGAueGAhuGAreGAr+GAnuGAsDog4YCx4YCZ4YCs4YC54YCc4YCs4YCU4YCsIOGAmeGAr+GAn+GAmeGBvOGAkuGAuSDhgKHhgIXhgLnhgJfhgJvhgKzhgJ/hgK7hgLjhgJnhgLk='),
(59, 'https://androlover.com/islamic/images/img59.jpg', 'https://androlover.com/islamic/books/B59.pdf', 'IB59.pdf', '4pyUIOGAnuGAmeGAreGAr+GAhOGAueGAuOGAseGAlOGArOGAgOGAueGAgeGAtiDhgKHhgIXhgaXhgJzhgKzhgJnhgLnhgJfhgJ/hgK/hgJ7hgK/hgJDhgIXhgLzhgJrhgLnhgIXhgLbhgK8=', '4pyUIEZpbGUgU2l6ZTogMTIuNyBNQg==', '4pyUIOGAu+GAleGAlOGAueGAhuGAreGAr+GAseGAm+GAuOGAnuGArOGAuOGAnuGAsDog4YCh4YCc4YC54YCf4YCC4YC64YC5IOGAseGAmeGArOGAueGAnOGArOGAlOGArOGAmeGAr+GAluGAueGAnuGAruGAgOGArOGAm+GAruGAmeGAr+GAn+GAmeGBvOGAkuGAueGAmuGAsOGAheGAvOGAluGAuSA='),
(60, 'https://androlover.com/islamic/images/img60.jpg', 'https://androlover.com/islamic/books/B60.pdf', 'IB60.pdf', '4pyUIOGAoeGAheGBpeGAnOGArOGAmeGAueGAgOGAseGAleGAuOGAseGAnuGArCDhgIfhgJThgK7hgLjhgJDhgK3hgK/hgpThgKHhgIHhgLzhgIThgLnhgLfhgKHhgLHhgJvhgLg=', '4pyUIEZpbGUgU2l6ZTogMy4wMSBNQg==', '4pyUIOGAu+GAleGAlOGAueGAhuGAreGAr+GAnuGAsDog4YCx4YCZ4YCs4YC54YCc4YCs4YCU4YCsIOGAmeGAr+GAn+GAmeGBvOGAkuGAuSDhgJvhgJbhgK7hgLjhgIDhgLk='),
(61, 'https://androlover.com/islamic/images/img61.jpg', 'https://androlover.com/islamic/books/B61.pdf', 'IB61.pdf', '4pyUIOGAgeGAhOGAueGAleGAvOGAlOGAueGAuOGBj+GAoeGAgeGAvOGAhOGAueGAt+GAoeGAseGAm+GAuOGCj+GAveGAhOGAueGAtyDhgJrhgIThgLnhgLjhgY/hgKHhgIbhgIThgLnhgLfhgKHhgJDhgJThgLnhgLg=', '4pyUIEZpbGUgU2l6ZTogMy45NSBNQg==', '4pyUIOGAu+GAleGAlOGAueGAhuGAreGAr+GAnuGAsDog4YCD4YCs4YCH4YCuIOGAseGAmeGArOGAueGAnOGAneGAriBLLkIg4YCF4YCt4YCv4YC44YCc4YC84YCE4YC5ICjhgJnhgJ/hgLnhgJnhgLDhgJLhgK4p'),
(62, 'https://androlover.com/islamic/images/img62.jpg', 'https://androlover.com/islamic/books/B62.pdf', 'IB62.pdf', '4pyUIOGAn+GAheGAueGAguGAuuGAm+GAruGAgeGAryDhgJ7hgK/hgLHhgJDhgJ7hgJThgIXhgKzhgJDhgJnhgLnhgLg=', '4pyUIEZpbGUgU2l6ZTogMi44NCBNQg==', '4pyUIOGAu+GAleGAs+GAheGAr+GAnuGAsDog4YCx4YCZ4YCs4YC54YCc4YCs4YCU4YCsIOGCj+GAsOGAuOGAm+GAueGAmeGAr+GAn+GAmeGBvOGAkuGAuS3hgKXhgK7hgLjhgIHhgIThgLnhgLHhgJvhgoo='),
(63, 'https://androlover.com/islamic/images/img63.jpg', 'https://androlover.com/islamic/books/B63.pdf', 'IB63.pdf', '4pyUIOGAnOGAsOGAseGAu+GAleGArOGAnuGAmeGAuuGAveGAmeGAveGAkOGAueGAkOGAmeGAueGAuOGAkOGAhOGAueGCj+GAveGAhOGAueGAtyDhgILhgK/hgJThgJ/hgLnhgIDhgIThgLnhgLjhgIXhgIThgLnhgJjhgJ3hgJXhgK3hgK/hgIThgLnhgJvhgL3hgIThgLk=', '4pyUIEZpbGUgU2l6ZTogMy4xMCBNQg==', '4pyUIOGAu+GAleGAlOGAueGAhuGAreGAr+GAnuGAsDog4YCx4YCZ4YCs4YC54YCc4YCs4YCU4YCsIOGAmeGAr+GAn+GAmeGBvOGAkuGAuSDhgKHhgIXhgLnhgJfhgJvhgKzhgJ/hgK7hgLjhgJnhgLkg'),
(64, 'https://androlover.com/islamic/images/img64.jpg', 'https://androlover.com/islamic/books/B64.pdf', 'IB64.pdf', '4pyUIOGAgOGAuuGAmeGAueGAuOGAu+GAmeGAkOGAueGAgOGAr+GAm+GAueGAoeGArOGAlOGAuSDhgIHhgJ7hgJnhgLnhgJbhgJDhgLnhgLvhgIHhgIThgLnhgLjhgo/hgL3hgIThgLnhgLcg4YCh4YCu4YCG4YCs4YCx4YCc4YCF4YCd4YCr4YC44YCX4YC5', '4pyUIEZpbGUgU2l6ZTogMS44MSBNQg==', '4pyUIOGAu+GAleGAlOGAueGAhuGAreGAr+GAseGAm+GAuOGAnuGArOGAuOGAnuGAsDog4YCx4YCZ4YCs4YC54YCc4YCd4YCuIOGAmeGAr+GAn+GAmeGBvOGAkuGAuSDhgJ7hgLzhgKzhgJ/hgK3hgJvhgLkgKOGAmeGAn+GAueGAmeGAsOGAkuGArik='),
(65, 'https://androlover.com/islamic/images/img65.jpg', 'https://androlover.com/islamic/books/B65.pdf', 'IB65.pdf', '4pyUIOGAguGAuuGCj+GBt+GAnuGAueGAkOGAvOGAhOGAuSDhgLHhgIbhgLzhgJnhgLrhgLPhgK3hgLjhgJ7hgKzhgLjhgIHhgLrhgIThgLnhgLg=', '4pyUIEZpbGUgU2l6ZTogMi42NiBNQg==', '4pyUIOGAu+GAleGAlOGAueGAhuGAreGAr+GAnuGAsDog4YCx4YCZ4YCs4YC54YCc4YCd4YCuIOGAoeGAl+GAsOGAluGAreGCkOGAr+GAreGAuOGAh+GAuSAtIOGAnOGAvOGAhOGAueGAseGAh+GArOGAueGAmeGAreGAr+GAuCAo4YCZ4YCf4YC54YCZ4YCw4YCS4YCuKQ=='),
(66, 'https://androlover.com/islamic/images/img66.jpg', 'https://androlover.com/islamic/books/B66.pdf', 'IB66.pdf', '4pyUIOGAm+GAmeGAueGChuGAvOGArOGAlOGAueGCj+GAveGAhOGAueGAt+GAl+GAkuGAueGAm+GAuSDhgIXhgIXhgLnhgJXhgLzhgLI=', '4pyUIEZpbGUgU2l6ZTogMy44NyBNQg==', '4pyUIOGAheGAr+GAseGAhuGArOGAhOGAueGAuOGAkOGAhOGAueGAu+GAleGAnuGAsDog4YCx4YCZ4YCs4YC54YCc4YCs4YCU4YCsIOGAn+GArOKAi+GAluGAvOGAh+GAuSDhgKHhgJfhgbrhgJLhgLzhgJzhgLnhgIXhgJzhgKzhgJnhgLk='),
(72, 'https://androlover.com/islamic/images/img71.jpg', 'https://androlover.com/islamic/books/B71.pdf', 'IB71.pdf', '4pyUIOGAguGAuuGAlOGArOGAh+GArOGAn+GAueGBj+GAleGAiuGAkOGAueGAgeGAuuGAgOGAueGAmeGAuuGArOGAuA==', '4pyUIEZpbGUgU2l6ZTogNjAxIEtC', '4pyUIOGAu+GAleGAlOGAueGAhuGAreGAr+GAnuGAsDog4YCx4YCZ4YCs4YC54YCc4YCd4YCuIOGAn+GArOKAi+GAluGAvOGAh+GAuSDhgJnhgK/hgJ/hgJnhgbzhgJLhgLkg4YCh4YCE4YC54YCZ4YC54YCb4YCs4YC44YCU4YC5'),
(67, 'https://androlover.com/islamic/images/img67.jpg', 'https://androlover.com/islamic/books/B67.pdf', 'IB67.pdf', '4pyUIOGAm+GAmeGAueGChuGAvOGArOGAlOGAueGCj+GAveGAhOGAueGAtyDhgJfhgJLhgLnhgJvhgLnhgIXhgIXhgLnhgJXhgLzhgLI=', '4pyUIEZpbGUgU2l6ZTogOTA2IEtC', '4pyUIOGAu+GAleGAs+GAheGAr+GAnuGAsDog4YCD4YCs4YCH4YCuIOGAnuGAruGAm+GAreGAleGAuuGAtuGAgeGAuuGAruGAoeGAnOGAueGAn+GAguGAuuGAuSDhgLHhgJnhgKzhgLnhgJzhgKzhgJThgKzhgJnhgK/hgJ/hgJnhgbzhgJLhgLnhgJ/hgKzhgJvhgL3hgIThgLnhgJnhgLk='),
(68, 'https://androlover.com/islamic/images/img68.jpg', 'https://androlover.com/islamic/books/B68.pdf', 'IB68.pdf', '4pyUIOGAgOGAuuGAmeGAueGAuOGAu+GAmeGAkOGAueGAgOGAr+GAm+GAueGAoeGArOGAlOGAueGAnOGArCDhgLHhgJDhgKzhgIThgLnhgLjhgIbhgK/hgLHhgJDhgKzhgLnhgJnhgLrhgKzhgLjhgo/hgL3hgIThgLnhgLcg4YCA4YCv4YCR4YC24YCv4YC44YCZ4YC64YCs4YC4', '4pyUIEZpbGUgU2l6ZTogMTAuMSBNQg==', '4pyUIFJlZnVyYmlzaGVkIFNjYW4gQm9vaw=='),
(69, 'https://androlover.com/islamic/images/img69.jpg', 'https://androlover.com/islamic/books/B69.pdf', 'IB69.pdf', '4pyUIOGAkOGAmeGAlOGAueGAseGAkOGArOGAueGAu+GAmeGAkOGAueGBjyDhgKHhgK3hgJnhgLnhgLHhgJHhgKzhgIThgLnhgLHhgJvhgLjhgJjhgYDhgKHhgLHhgJXhgZog4YCx4YCF4YCs4YCS4YCA4YKP4YC94YCE4YC54YC34YCh4YCx4YC74YCW', '4pyUIEZpbGUgU2l6ZTogMi42OSBNQg==', '4pyUIFJlZnVyYmlzaGVkIFNjYW4gQm9vaw=='),
(71, 'https://androlover.com/islamic/images/img70.jpg', 'https://androlover.com/islamic/books/B70.pdf', 'IB70.pdf', '4pyUIOGAleGAuuGArOGAuOGAm+GAiuGAueGBjyDhgJHhgLDhgLjhgLvhgIHhgKzhgLjhgJ7hgIrhgLnhgLcg4YCh4YCs4YCU4YCt4YCe4YCE4YC54YCZ4YC64YCs4YC4', '4pyUIEZpbGUgU2l6ZTogMi41MiBNQg==', '4pyUIOGAu+GAleGAlOGAueGAhuGAreGAr+GAnuGAsDog4YCx4YCZ4YCs4YC54YCc4YCd4YCuIOGAoeGAheGAueGAl+GAm+GArOGAn+GAruGAuOGAmeGAuSAo4YCx4YCb4YCU4YCuLeGAmeGAn+GAueGAmeGAsOGAkuGArik='),
(73, 'https://androlover.com/islamic/images/img72.jpg', 'https://androlover.com/islamic/books/B72.pdf', 'IB72.pdf', '4pyUIOGAu+GAmeGAlOGAueGAmeGArOGCj+GAreGAr+GAhOGAueGAhOGAtuGCj+GAveGAhOGAueGAtyDhgKHhgIXhgaXhgJzhgKzhgJnhgLnhgJ7hgKzhgJ7hgJThgKw=', '4pyUIEZpbGUgU2l6ZTogMzIuMSBNQg==', '4pyUIFJlZnVyYmlzaGVkIFNjYW4gQm9vaw=='),
(74, 'https://androlover.com/islamic/images/img73.jpg', 'https://androlover.com/islamic/books/B73.pdf', 'IB73.pdf', '4pyUIOGAgOGAr+GAm+GAueGAl+GArOGAlOGAruGBj+GAleGAiuGAkOGAueGAgeGAuuGAgOGAueGAmeGAuuGArOGAuA==', '4pyUIEZpbGUgU2l6ZTogMS42MyBNQg==', '4pyUIOGAu+GAleGAlOGAueGAhuGAreGAr+GAnuGAsDog4YCx4YCZ4YCs4YC54YCc4YCd4YCuIOGAn+GArOKAi+GAluGAvOGAh+GAuSDhgJnhgK/hgJ/hgJnhgbzhgJLhgLkg4YCZ4YCs4YCZ4YC54YCG4YCs'),
(75, 'https://androlover.com/islamic/images/img74.jpg', 'https://androlover.com/islamic/books/B74.pdf', 'IB74.pdf', '4pyUIOGAleGAm+GAueGAkuGAn+GAueGAn+GAsOGAnuGAiuGAuSDhgJbhgJvhgIfhgLk=', '4pyUIEZpbGUgU2l6ZTogNC4wOSBNQg==', '4pyUIOGAu+GAleGAlOGAueGAhuGAreGAr+GAnuGAsDog4YCx4YCZ4YCs4YC54YCc4YCs4YCU4YCsIOGAn+GArOGAm+GAsOGAlOGAueGAnOGAsOGAnOGArOGAnuGAuSA='),
(76, 'https://androlover.com/islamic/images/img75.jpg', 'https://androlover.com/islamic/books/B75.pdf', 'IB75.pdf', '4pyUIOGAleGAlOGAueGAuOGAneGAq+GCj+GAvOGAmuGAuSDhgLvhgJnhgJThgLnhgJnhgKzhgIDhgJfhgLrhgKwg4YCA4YCF4YC84YCu4YCS4YCr4YCZ4YC64YCs4YC4', '4pyUIEZpbGUgU2l6ZTogNS4wMCBNQg==', '4pyUIOGAu+GAleGAs+GAheGAr+GAnuGAsDog4YCV4YCU4YC54YC44YCd4YCr4YKP4YC84YCa4YC5ICjhgJvhgJnhgIrhgLnhgLjhgJ7hgIThgLnhgLgp'),
(77, 'https://androlover.com/islamic/images/img76.jpg', 'https://androlover.com/islamic/books/B76.pdf', 'IB76.pdf', '4pyUIOGAnuGAmeGAr+GAkuGBteGAm+GArOGAseGAoeGArOGAgOGAueGAmeGAvSDhgJXhgK/hgJzhgLLhgJzhgLbhgK/hgLjhgJnhgLrhgKzhgLgg', '4pyUIEZpbGUgU2l6ZTogNy40MCBNQg==', '4pyUIOGAu+GAleGAs+GAheGAr+GAnuGAsDog4YCh4YCU4YC54YCd4YCb4YC54YCb4YC94YCs4YC44YCf4YC5ICjhgIDhgJvhgL3hgLnhgJnhgK7hgJvhgK4p'),
(78, 'https://androlover.com/islamic/images/img77.jpg', 'https://androlover.com/islamic/books/B77.pdf', 'IB77.pdf', '4pyUIOGAl+GAmeGArOGAmeGAvOGAkOGAueGAheGAnOGAhOGAuSAo4YCd4YCrKSDhgJXhgJ7hgK4=', '4pyUIEZpbGUgU2l6ZTogMS40MSBNQg==', '4pyUIOGAu+GAleGAs+GAheGAr+GAnuGAsDog4YCV4YCe4YCu4YCA4YC84YCU4YC54YCC4YCb4YCA4YC54YCM4YCs4YCU4YCB4YC64YCz4YCV4YC5'),
(79, 'https://androlover.com/islamic/images/img78.jpg', 'https://androlover.com/islamic/books/B78.pdf', 'IB78.pdf', '4pyUIOGAoeGAtuGAt+GAmOGAvOGAmuGAuSDhgJ/hgJnhgLnhgIfhgKzhgLjhgJLhgLk=', '4pyUIEZpbGUgU2l6ZTogMi44NSBNQg==', '4pyUIOGAu+GAleGAs+GAheGAr+GAnuGAsDog4YKQ4YKI4YCt4YCA4YC5IOGAmeGAr+GAn+GAmeGBvOGAkuGAuSDhgJ7hgLzhgKzhgJ/hgK3hgJvhgLkgKOGAmeGAh+GAvOGArOGAseGAn+GAm+GArik='),
(80, 'https://androlover.com/islamic/images/img79.jpg', 'https://androlover.com/islamic/books/B79.pdf', 'IB79.pdf', '4pyUIOGAkOGAmeGAlOGAueGAseGAkOGArOGAueGAu+GAmeGAkOGAuSjhgIbhgLwp4YGPIOGAseGAkOGArOGAhOGAueGAuOGAhuGAr+GAseGAkOGArOGAueGAmeGAuuGArOGAuA==', '4pyUIEZpbGUgU2l6ZTogMi44NyBNQg==', '4pyUIFJlZnVyYmlzaGVkIFNjYW4gQm9vaw=='),
(81, 'https://androlover.com/islamic/images/img80.jpg', 'https://androlover.com/islamic/books/B80.pdf', 'IB80.pdf', '4pyUIOGAgOGAmeGBu+GArOGAt+GAheGAtuGAu+GAlSDhgJDhgJnhgJThgLnhgLHhgJDhgKzhgLk=', '4pyUIEZpbGUgU2l6ZTogMjEuNSBNQg==', '4pyUIOGAu+GAleGAs+GAheGAr+GAnuGAsDog4YCd4YCr4YC44YCB4YCa4YC54YCZ4YCx4YCZ4YCs4YCE4YC54YCZ4YCE4YC54YC44YKP4YCt4YCv4YCE4YC5'),
(82, 'https://androlover.com/islamic/images/img81.jpg', 'https://androlover.com/islamic/books/B81.pdf', 'IB81.pdf', '4pyUIOGAu+GAmeGAlOGAueGAmeGArOGAt+GAnOGAvOGAkOGAueGAnOGAleGAueGAseGAm+GAuCDhgb7hgIDhgK3hgLPhgLjhgJXhgJnhgLnhgLjhgJnhgogg4YCe4YCZ4YCt4YCv4YCE4YC54YC44YCd4YCE4YC5IOGAmeGAvOGAkOGAueGAheGAnOGAhOGAueGAmeGAuuGArOGAuA==', '4pyUIEZpbGUgU2l6ZTogMTQuMiBNQg==', '4pyUIOGAu+GAleGAs+GAheGAr+GAnuGAsDog4YCd4YCr4YC44YCB4YCa4YC54YCZ4YCx4YCZ4YCs4YCE4YC54YCZ4YCE4YC54YC44YKP4YCt4YCv4YCE4YC5'),
(83, 'https://androlover.com/islamic/images/img82.jpg', 'https://androlover.com/islamic/books/B82.pdf', 'IB82.pdf', '4pyUIOGAgOGAr+GAm+GAueGAmOGArOGAlOGAruGAgOGAseGAleGAuOGAseGAnuGArCDhgJ7hgIThgLnhgIHhgJThgLnhgLjhgIXhgKw=', '4pyUIEZpbGUgU2l6ZTogMi43MiBNQg==', '4pyUIOGAu+GAleGAs+GAheGAr+GAnuGAsDog4YCZ4YCv4YCW4YC54YCe4YCuIOGCj+GAsOGAuOGAm+GAueGAmeGAr+GAn+GAmeGBvOGAkuGAuQ=='),
(84, 'https://androlover.com/islamic/images/img83.jpg', 'https://androlover.com/islamic/books/B83.pdf', 'IB83.pdf', '4pyUIOGAu+GAmeGAlOGAueGAmeGArOGCj+GAreGAr+GAhOGAueGAhOGAtuGAnuGArOGAuCDhgKHhgIXhgaXhgJzhgKzhgJnhgLnhgJjhgKzhgJ7hgKzhgJ3hgIThgLnhgJDhgK3hgK/hgpThgKHhgKzhgLgg4YCx4YCb4YC94YC44YC74YCZ4YCU4YC54YCZ4YCs4YCZ4YCE4YC54YC44YCZ4YC64YCs4YC44YCAIOGAgeGAuuGAruGAuOGAu+GAmeGAveGAhOGAueGAt+GAgeGAsuGAt+GAleGAtuGArw==', '4pyUIEZpbGUgU2l6ZTogNC4yMiBNQg==', '4pyUIOGAu+GAleGAs+GAheGAr+GAnuGAsDog4YCx4YCH4YCa4YC64YCx4YCA4YC64YCs4YC54YCR4YCE4YC5IOGAl+GAreGAr+GAnOGAueGAmeGAveGAtOGAuOGBvuGAgOGAruGAuCDhgJjhgJvhgL3hgIThgLk=');

-- --------------------------------------------------------

--
-- Table structure for table `is_ads`
--

CREATE TABLE `is_ads` (
  `id` int(11) NOT NULL,
  `image` varchar(1000) NOT NULL,
  `state` varchar(1000) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Dumping data for table `is_ads`
--

INSERT INTO `is_ads` (`id`, `image`, `state`) VALUES
(1, 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone8-select-2019-family?wid=882&amp;hei=1058&amp;fmt=jpeg&amp;qlt=80&amp;op_usm=0.5,0.5&amp;.v=1550795431127', '');

-- --------------------------------------------------------

--
-- Table structure for table `itbooks`
--

CREATE TABLE `itbooks` (
  `id` int(11) NOT NULL,
  `image_url` varchar(1000) NOT NULL,
  `book_url` varchar(1000) NOT NULL,
  `book_name` varchar(1000) NOT NULL,
  `title` varchar(1000) NOT NULL,
  `size` varchar(1000) NOT NULL,
  `des` text NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Dumping data for table `itbooks`
--

INSERT INTO `itbooks` (`id`, `image_url`, `book_url`, `book_name`, `title`, `size`, `des`) VALUES
(1, 'https://androlover.com/itlibrary/images/img1.jpg', 'https://androlover.com/itlibrary/books/B1.pdf', 'ITB1.pdf', '4pyUIEFuZHJvaWQgQXBwbGljYXRpb24g4YCx4YCb4YC44YCe4YCs4YC44YCW4YCU4YC54YCQ4YCu4YC44YC74YCB4YCE4YC54YC44YCG4YCt4YCv4YCE4YC54YCb4YCsIOGAoeGAseGAu+GAgeGAgeGAtuGAnuGAseGAmOGArOGAkOGAm+GArOGAuOGAmeGAuuGArOGAuA==', '4pyUIEZpbGUgU2l6ZSAtIDEyIE1C', '4pyUIOGBgOGAhOGAueGAuOGAn+GAreGAlOGAueGAuCBCLkMuVGVjaChVQ1MuWSksIEQuQi5TKFkuSS5FY28p'),
(2, 'https://androlover.com/itlibrary/images/img2.png', 'https://androlover.com/itlibrary/books/B2.pdf', 'ITB2.pdf', '4pyUIEFuZHJvaWQg4YCx4YCV4YGa4YCZ4YC94YCc4YCA4YC54YCx4YCQ4YC84YKV4YCe4YC24YCv4YC4IOGAlOGAiuGAueGAuOGAleGAiuGArA==', '4pyUIEZpbGUgU2l6ZSAtIDE5IE1C', '4pyUIOGAseGAm+GAuOGAnuGArOGAuOGAnuGAsCAgICDhgLggIOGAnuGAlOGAueGAuOGAkeGAreGAr+GAgOGAuSAo4YCx4YCb4YKK4YCb4YCt4YCV4YC5KQ=='),
(3, 'https://androlover.com/itlibrary/images/img3.jpg', 'https://androlover.com/itlibrary/books/B3.pdf', 'ITB3.pdf', '4pyUIExhcHRvcCDhgIDhgLzhgJThgLnhgJXhgLrhgLThgJDhgKzhgLvhgJXhgLPhgLvhgJXhgIThgLnhgJThgIrhgLnhgLjhgo/hgL3hgIThgLnhgLcg4YCe4YCt4YCe4YCE4YC54YC34YCF4YCb4YCs4YCZ4YC64YCs4YC4', '4pyUIEZpbGUgU2l6ZSAtIDEyLjkgTUIg', '4pyUIOGAseGAm+GAuOGAnuGArOGAuOGAnuGAsCAgICDhgLggIOGAnuGAlOGAueGAuOGAkeGAreGAr+GAgOGAuSAo4YCx4YCb4YKK4YCb4YCt4YCV4YC5KQ=='),
(4, 'https://androlover.com/itlibrary/images/img4.jpg', 'https://androlover.com/itlibrary/books/B4.pdf', 'ITB4.pdf', '4pyUIOGAmeGAu+GAluGAheGAueGAmeGAseGAlOGBvuGAgOGAtuGAs+GAseGAkOGAvOGCleGAseGAlOGBvuGAgCDhgIDhgLzhgJThgLnhgJXhgLrhgLThgJDhgKzhgJnhgL0g4YC74YCV4YCe4YCU4YCs4YCZ4YC64YCs4YC44YCx4YC74YCW4YCb4YC94YCE4YC54YC44YCU4YCK4YC54YC4', '4pyUIEZpbGUgU2l6ZSAtIDExIE1C', '4pyUIOGAseGAm+GAuOGAnuGArOGAuOGAnuGAsCDhgLgg4YCl4YCs4YCP4YC54YG+4YCA4YC84YCa4YC5'),
(5, 'https://androlover.com/itlibrary/images/img5.png', 'https://androlover.com/itlibrary/books/B5.pdf', 'ITB5.pdf', '4pyUIFBob3Rvc2hvcCBDUyBUb29scyDhgJnhgLrhgKzhgLjhgY/hgJzhgojhgK3hgpXhgYDhgL3hgIDhgLnhgIHhgLrhgIDhgLk=', '4pyUIEZpbGUgU2l6ZSAtIDkuNyBNQg==', '4pyUIOGAseGAm+GAuOGAnuGArOGAuOGAnuGAsCDhgLgg4YCZ4YC64YCz4YCt4YC44YCG4YCA4YC5'),
(6, 'https://androlover.com/itlibrary/images/img6.jpg', 'https://androlover.com/itlibrary/books/B6.pdf', 'ITB6.pdf', '4pyUIOGAgOGAvOGAlOGAueGAleGAuuGAtOGAkOGArOGAleGAiuGArOGAm+GAveGAhOGAueGAnOGAgOGAueGAheGAvOGAsiAoQ29tcHV0ZXIgU3lzdGVtIEFkbWluaXN0cmF0aW9uKQ==', '4pyUIEZpbGUgU2l6ZSAtIDE4LjE0IE1C', '4pyUIOGAheGArOGAseGAm+GAuOGAhuGAm+GArC3hgJvhgLLhgJnhgIThgLnhgLjhgLHhgKHhgKzhgIThgLkgKFJheS1FbGVjdHJvbmljKQ=='),
(7, 'https://androlover.com/itlibrary/images/img7.jpg', 'https://androlover.com/itlibrary/books/B7.pdf', 'ITB7.pdf', '4pyUIE1vYmlsZSBQaG9uZSDhgY8gSGFyZHdhcmUg4YCV4YCF4YGl4YCK4YC54YC44YCZ4YC64YCs4YC4IOGAu+GAleGAs+GAu+GAleGAhOGAueGAseGAm+GAuCDhgJThgIrhgLnhgLjhgJzhgJnhgLnhgLjhgJnhgLrhgKzhgLg=', '4pyUIEZpbGUgU2l6ZSAtIDcuMk1C', '4pyUIOGAseGAm+GAuOGAnuGArOGAuOGAnuGAsCAtICDhgJvhgLLhgJnhgIThgLnhgLjhgLHhgKHhgKzhgIThgLkoIFJheSBFbGVjdHJvbmljICk='),
(8, 'https://androlover.com/itlibrary/images/img8.png', 'https://androlover.com/itlibrary/books/B8.pdf', 'ITB8.pdf', '4pyUIFBob3Rvc2hvcCDhgY8g4YCc4YC94YC64YCz4YCt4YKV4YGA4YC94YCA4YC54YCB4YC64YCA4YC54YCZ4YC64YCs4YC4IA==', '4pyUIEZpbGUgU2l6ZSAtIDExLjk4IE1C', '4pyUIOGAseGAm+GAuOGAnuGArOGAuOGAnuGAsCDhgLgg4YCl4YCu4YC44YCx4YCh4YCs4YCE4YC54YKP4YCv4YCt4YCE4YC54YCx4YCZ4YCs4YC5'),
(9, 'https://androlover.com/itlibrary/images/img9.jpg', 'https://androlover.com/itlibrary/books/B9.pdf', 'ITB9.pdf', '4pyUIEZhY2Vib29rIFNhZmVseSBHdWlkZS3hgJzhgK/hgLbhgb/hgIHhgLPhgLbhgIXhgK3hgJDhgLnhgIHhgLrhgIXhgLzhgKwgZmFjZWJvb2sg4YCh4YCe4YCv4YC24YC44YC74YCV4YCz4YC74YCB4YCE4YC54YC4', '4pyUIEZpbGUgU2l6ZSAtICA5LjMyIE1C', '4pyUIOGAseGAm+GAuOGAnuGArOGAuOGAnuGAsCDhgLgg4YCZ4YCE4YC54YC44YCe4YCU4YC54YKU4YCx4YCh4YCs4YCE4YC5'),
(10, 'https://androlover.com/itlibrary/images/img10.jpg', 'https://androlover.com/itlibrary/books/B10.pdf', 'ITB10.pdf', '4pyUIERpZ2l0YWwgVmlkZW8gRWRpdGluZw==', '4pyUIEZpbGUgU2l6ZSAtIDEwLjggTUI=', '4pyUIOGAseGAm+GAuOGAnuGArOGAuOGAnuGAsCAgICDhgLggIOGAnuGAlOGAueGAuOGAkeGAreGAr+GAgOGAuSAo4YCx4YCb4YKK4YCb4YCt4YCV4YC5KQ=='),
(11, 'https://androlover.com/itlibrary/images/img11.png', 'https://androlover.com/itlibrary/books/B11.pdf', 'ITB11.pdf', '4pyUIEVhc3kgQ29tcHV0ZXIgQmFzaWMt4YCc4YC84YCa4YC54YCA4YCw4YCx4YCc4YC34YCc4YCsIOGAoeGAseGAu+GAgeGAgeGAtuGAgOGAvOGAlOGAueGAleGAuuGAtCDhgJDhgKw=', '4pyUIEZpbGUgU2l6ZSAtIDE1LjU0IE1C', '4pyUIOGAseGAm+GAuOGAnuGArOGAuOGAnuGAsCDhgLgg4YCl4YCu4YC44YCZ4YC64YCz4YCt4YC44YCe4YCw4YCb'),
(12, 'https://androlover.com/itlibrary/images/img12.jpg', 'https://androlover.com/itlibrary/books/B12.pdf', 'ITB12.pdf', '4pyUIEFuZHJvaWQgQXBwbGljYXRpb24g4YCZ4YC64YCs4YC44YCx4YCb4YC44YCG4YC84YCy4YCW4YCU4YC54YCQ4YCu4YC44YCc4YCt4YCv4YCe4YCw4YCZ4YC64YCs4YC44YCc4YCA4YC54YCF4YC84YCy', '4pyUIEZpbGUgU2l6ZSAtIDExIE1C', '4pyUIOGAheGArOGAseGAm+GAuOGAnuGAsCAtIOGAm+GAsuGAmeGAhOGAueGAuOGAseGAoeGArOGAhOGAuQ=='),
(13, 'https://androlover.com/itlibrary/images/img13.jpg', 'https://androlover.com/itlibrary/books/B13.pdf', 'ITB13.pdf', '4pyUIOGAgOGAreGAr+GAmuGAueGAkOGAreGAr+GAhOGAueGAseGAnOGAt+GAnOGArCBKYXZhIOGAnuGAhOGAueGAgeGAlOGAueGAuOGAheGArA==', '4pyUIEZpbGUgU2l6ZSAtIDUuNzggTUI=', '4pyUIOGAheGArOGAseGAm+GAuOGAnuGAsCAtIMOXw5fDl8OXw5c='),
(14, 'https://androlover.com/itlibrary/images/img14.jpg', 'https://androlover.com/itlibrary/books/B14.pdf', 'ITB14.pdf', '4pyUIOGAnOGAvOGAmuGAueGAgOGAsOGAseGAnOGAt+GAnOGArCBKYXZhIOGAnuGAhOGAueGAgeGAlOGAueGAuOGAheGArOGAmeGAuuGArOGAuA==', '4pyUIEZpbGUgU2l6ZSAtIDMwIE1C', '4pyUIOGAheGArOGAseGAm+GAuOGAnuGAsCAtIOGAhuGCj+GBteGAseGAoeGArOGAhOGAuQ=='),
(15, 'https://androlover.com/itlibrary/images/img15.jpg', 'https://androlover.com/itlibrary/books/B15.pdf', 'ITB15.pdf', '4pyUICDhgJvhgK3hgK/hgLjhgJ7hgKzhgLjhgIXhgLzhgKzhgJHhgK3hgK/hgLjhgJHhgLzhgIThgLnhgLjhgLHhgJzhgLfhgJzhgKzhgLvhgIHhgIThgLnhgLggSG9uZXN0IEhhY2tpbmc=', '4pyUIEZpbGUgU2l6ZSAtIDE4LjUgTUI=', '4pyUICDhgIXhgKzhgLHhgJvhgLjhgJ7hgLAgLSDhgJ7hgJThgLnhgLjhgJHhgK3hgK/hgIDhgLko4YCx4YCb4YKK4YCb4YCt4YCV4YC5KQ=='),
(16, 'https://androlover.com/itlibrary/images/img16.jpg', 'https://androlover.com/itlibrary/books/B16.pdf', 'ITB16.pdf', '4pyUIOGAgOGAreGAr+GAmuGAueGAkOGAreGAr+GAhOGAueGAseGAnOGAt+GAnOGArCBZb3V0dWJlIOGAnuGAhOGAueGAgeGAlOGAueGAuOGAheGArA==', '4pyUIEZpbGUgU2l6ZSAtIDcuOCBNQg==', '4pyUIOGAheGArOGAseGAm+GAuOGAnuGAsCAtIOGApeGAruGAuOGAseGAnuGArOGAhOGAueGAuOGAneGAhOGAueGAuCjhgJXhgJThgLnhgLjhgIHhgLrhgJrhgLnhgJvhgK4p'),
(17, 'https://androlover.com/itlibrary/images/img17.jpg', 'https://androlover.com/itlibrary/books/B17.pdf', 'ITB17.pdf', '4pyUIOGAheGAmeGAkOGAueGAgOGAuuGAgOGAuiBpUGhvbmUg4YCh4YCe4YC24YCv4YC44YC74YCV4YCz4YCU4YCK4YC54YC4', '4pyUIEZpbGUgU2l6ZSA6IDMyLjQxIE1C', '4pyUIOGAheGArOGAseGAm+GAuOGAnuGAsC4uLi7hgLHhgJThgIfhgKzhgLHhgKHhgKzhgIThgLko4YCZ4YCt4YCv4YC44YCe4YCt4YG+4YCA4YCs4YC4KQ=='),
(18, 'https://androlover.com/itlibrary/images/img18.jpg', 'https://androlover.com/itlibrary/books/B18.pdf', 'ITB18.pdf', '4pyUIEludGVybmV0X1NlY3VyaXR5IOGAheGArOGAoeGAr+GAleGAuQ==', '4pyUIEZpbGUgU2l6ZSAtIDEzLjA0IE1C', '4pyUIOGAheGArOGAseGAm+GAuOGAhuGAm+GArCAtIOGAmeGAreGAuuGAs+GAuOGAnuGAsOGAmw=='),
(19, 'https://androlover.com/itlibrary/images/img19.jpg', 'https://androlover.com/itlibrary/books/B19.pdf', 'ITB19.pdf', '4pyUIOGAoeGAnuGAtuGAr+GAuOGAgeGAuuGAgOGAvOGAlOGAueGAmuGAgOGAueGCj+GAveGAhOGAueGAtyDhgKHhgLHhgYDhgLjhgJzhgL3hgJnhgLnhgLjhgJHhgK3hgJThgLnhgLjhgIHhgLrhgLPhgJXhgLnhgLvhgIHhgIThgLnhgLgg4YCU4YCK4YC54YC44YCV4YCK4YCs', '4pyUIEZpbGUgU2l6ZSAtIDExLjA3IE1C', '4pyUIOGAheGArOGAseGAm+GAuOGAnuGAsCAtIOGAm+GAsuGAmeGAhOGAueGAuOGAseGAoeGArOGAhOGAuSAoUmF5LUVsZWN0cm9uaWMp'),
(20, 'https://androlover.com/itlibrary/images/img20.png', 'https://androlover.com/itlibrary/books/B20.pdf', 'ITB20.pdf', '4pyUIFdpcmVsZXNzIOGAkeGAreGAr+GAuOGAseGAluGArOGAgOGAueGAu+GAgeGAhOGAueGAuOGAheGAmeGAueGAuOGAnuGAleGAueGAgeGAuuGAgOGAueGAmeGAuuGArOGAuA==', '4pyUIEZpbGUgU2l6ZSAtIDIzLjUgTUI=', '4pyUIOGAheGArOGAseGAm+GAuOGAhuGAm+GArCAtIOGAm+GAsuGAmeGAhOGAueGAuOGAseGAoeGArOGAhOGAuQ=='),
(21, 'https://androlover.com/itlibrary/images/img21.png', 'https://androlover.com/itlibrary/books/B21.pdf', 'ITB21.pdf', '4pyUIOGAgOGAvOGAlOGAueGAleGAuuGAtOGAkOGArOGAleGAiuGArOGAm+GAveGAhOGAueGAnOGAgOGAueGAheGAvOGAsuGAheGArOGAoeGAr+GAleGAuQ==', '4pyUIEZpbGUgU2l6ZSAtIDEzLjczIE1C', '4pyUIOGAheGArOGAseGAm+GAuOGAhuGAm+GArCAtIOGAm+GAsuGAmeGAhOGAueGAuOGAseGAoeGArOGAhOGAuSAoUmF5LUVsZWN0cm9uaWMp'),
(22, 'https://androlover.com/itlibrary/images/img22.jpg', 'https://androlover.com/itlibrary/books/B22.pdf', 'ITB22.pdf', '4pyUIEFuZHJvaWQg4YCF4YCA4YC54YC74YCV4YCE4YC54YCG4YCb4YCs4YCc4YCA4YC54YCF4YC84YCy', '4pyUIEZpbGUgU2l6ZSAtIDcuMTEgTUI=', '4pyUIOGAheGArOGAseGAm+GAuOGAhuGAm+GArCAtIOGAm+GAsuGAmeGAhOGAueGAuOGAseGAoeGArOGAhOGAuSAoUmF5LUVsZWN0cm9uaWMp'),
(23, 'https://androlover.com/itlibrary/images/img23.jpg', 'https://androlover.com/itlibrary/books/B23.pdf', 'ITB23.pdf', '4pyUIE1vYmlsZSDhgJnhgK3hgLrhgLPhgLjhgIXhgLbhgK/hgKHhgJDhgLzhgIDhgLkgRmlybXdhcmUg4YCx4YCb4YC44YCe4YCs4YC44YCU4YCK4YC54YC4IA==', '4pyUIEZpbGUgU2l6ZSAtIDExLjg5IE1C', '4pyUIOGAheGArOGAseGAm+GAuOGAhuGAm+GArCAtIOGAm+GAsuGAmeGAhOGAueGAuOGAseGAoeGArOGAhOGAuShSYXktRWxlY3Ryb25pYyk='),
(24, 'https://androlover.com/itlibrary/images/img24.png', 'https://androlover.com/itlibrary/books/B24.pdf', 'ITB24.pdf', '4pyUIOGAmeGAreGAr+GAmOGAreGAr+GAhOGAueGAuOGAluGAr+GAlOGAueGAuCDhgKHhgIThgLnhgJDhgKzhgJThgIDhgLkg4YCh4YCe4YC24YCv4YC44YC74YCV4YCz4YCc4YCZ4YC54YC44YCK4YC84YCU4YC5', '4pyUIEZpbGUgU2l6ZSAtIDEuMDcgTUI=', '4pyUIOGAheGArOGAseGAm+GAuOGAhuGAm+GArCAtIFQuRS5D'),
(25, 'https://androlover.com/itlibrary/images/img25.png', 'https://androlover.com/itlibrary/books/B25.pdf', 'ITB25.pdf', '4pyUIFRIRSBNWUFOTUFS4oCZUyBBTkRST0lE', '4pyUIEZpbGUgU2l6ZSAtIDguODIgTUI=', '4pyUIOGAheGArOGAseGAm+GAuOGAhuGAm+GArCAtIEJvIFN1bm55IEx3aW4='),
(26, 'https://androlover.com/itlibrary/images/img26.jpg', 'https://androlover.com/itlibrary/books/B26.pdf', 'ITB26.pdf', '4pyUIFR3aXR0ZXIg4YCh4YCe4YC24YCv4YC44YC74YCV4YCz4YCU4YCK4YC54YC4', '4pyUIEZpbGUgU2l6ZSAtIDQuNDMgTUI=', '4pyUIOGAseGAm+GAuOGAnuGArOGAuOGAnuGAsCAtIOGAgOGAnOGAuuGArOGAoeGAreGAoeGAreGAnOGAvOGAhOGAuQ=='),
(27, 'https://androlover.com/itlibrary/images/img27.jpg', 'https://androlover.com/itlibrary/books/B27.pdf', 'ITB27.pdf', '4pyUIOGAoeGAhuGAhOGAueGAt+GAu+GAmeGAhOGAueGAtyDhgJLhgIXhgLnhgILhgLrhgIXhgLnhgJDhgJrhgLkg4YCT4YCs4YCQ4YC54YCV4YC24YCv4YCV4YCK4YCs', '4pyUIEZpbGUgU2l6ZSAtIDU0LjkyIE1C', '4pyUIOGAseGAm+GAuOGAnuGArOGAuOGAnuGAsCAtIOGAkOGAgOGBoOGAnuGAreGAr+GAnOGAuSDhgIXhgK3hgK/hgLjhgJ3hgIThgLnhgLg='),
(28, 'https://androlover.com/itlibrary/images/img28.jpg', 'https://androlover.com/itlibrary/books/B28.pdf', 'ITB28.pdf', '4pyUIOGAgOGAvOGAlOGAueGAleGAuuGAtOGAkOGArOGAkOGAleGAueGAhuGAhOGAueGAu+GAleGAsyDhgLvhgJXhgIThgLnhgJHhgK3hgJThgLnhgLjhgJ7hgK3hgJnhgLnhgLjhgJThgIrhgLnhgLjhgKHhgLHhgLvhgIHhgIHhgLbhgJ7hgLHhgJjhgKzhgJDhgJvhgKzhgLjhgJnhgLrhgKzhgLg=', '4pyUIEZpbGUgU2l6ZSAtIDE1LjIzIE1C', '4pyUIOGAseGAm+GAuOGAnuGArOGAuOGAnuGAsCAtIOGAmeGAuuGAreGAs+GAuOGAnuGAsOGAmw=='),
(29, 'https://androlover.com/itlibrary/images/img29.jpg', 'https://androlover.com/itlibrary/books/B29.pdf', 'ITB29.pdf', '4pyUIEF1dG9DQUQgMjAwMiA=', '4pyUIEZpbGUgU2l6ZSAtIDEwLjA4IE1C', '4pyUIOGAseGAm+GAuOGAnuGArOGAuOGAnuGAsCAtICoqKioqKg=='),
(30, 'https://androlover.com/itlibrary/images/img30.jpg', 'https://androlover.com/itlibrary/books/B30.pdf', 'ITB30.pdf', '4pyUIFdpZmkgSGFja2luZyBCYXNpYyDhgKHhgKzhgLjhgLHhgJbhgKzhgIDhgLnhgJHhgLzhgIThgLnhgLjhgLHhgJzhgLfhgJzhgKzhgLvhgIHhgIThgLnhgLgK', '4pyUIEZpbGUgU2l6ZSAtIDUuNTYgTUI=', '4pyUIOGAseGAm+GAuOGAnuGArOGAuOGAnuGAsCAtIOGAmeGAhOGAueGAuOGAheGAreGAr+GAuOGAm+GArOGAheGArA=='),
(31, 'https://androlover.com/itlibrary/images/img31.jpg', 'https://androlover.com/itlibrary/books/B31.pdf', 'ITB31.pdf', '4pyUIOGAgOGAvOGAlOGAueGAleGAuuGAtOGAkOGArOGAoeGAseGBvuGAgOGArOGAhOGAueGAuCDhgKHhgLHhgJ7hgLjhgIXhgK3hgJDhgLnhgJ7hgK3hgIXhgJvhgKw=', '4pyUIEZpbGUgU2l6ZSA6IDE2Ljk3IE1C', '4pyUIOGAseGAm+GAuOGAnuGArOGAuOGAnuGAsCAt4YCx4YCH4YCs4YC54YCc4YCE4YC54YC4'),
(32, 'https://androlover.com/itlibrary/images/img32.jpg', 'https://androlover.com/itlibrary/books/B32.pdf', 'ITB32.pdf', '4pyUIE1pY3Jvc29mdCBQb3dlciBQb2ludCAyMDA3', '4pyUIEZpbGUgU2l6ZSA6IDIuMjAgTUI=', '4pyUIOGAseGAm+GAuOGAnuGArOGAuOGAnuGAsCAtIEthIEthIEt1bg=='),
(33, 'https://androlover.com/itlibrary/images/img33.jpg', 'https://androlover.com/itlibrary/books/B33.pdf', 'ITB33.pdf', '4pyUIFBIUCDhgLHhgJzhgL3hgIDhgKzhgLjhgJHhgIXhgLnhgJnhgLrhgKzhgLg=', '4pyUIEZpbGUgU2l6ZSA6IDEzLjgzIE1C', '4pyUIOGAseGAm+GAuOGAnuGArOGAuOGAnuGAsCAtIOGAgOGAreGAr+GAseGAgOGAuuGArOGAuQ=='),
(34, 'https://androlover.com/itlibrary/images/img34.jpg', 'https://androlover.com/itlibrary/books/B34.pdf', 'ITB34.pdf', '4pyUIExlYXJuaW5nIExpbnV4', '4pyUIEZpbGUgU2l6ZSA6IDkuMTIgTUI=', '4pyUIOGAseGAm+GAuOGAnuGArOGAuOGAnuGAsCAtIOGAseGAh+GArOGAueGAnOGAhOGAueGAuA==');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `books`
--
ALTER TABLE `books`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `is_ads`
--
ALTER TABLE `is_ads`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `itbooks`
--
ALTER TABLE `itbooks`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `books`
--
ALTER TABLE `books`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=85;

--
-- AUTO_INCREMENT for table `is_ads`
--
ALTER TABLE `is_ads`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
